title: Alexander Ho
logo: docs / assets/IMG_6893.jpg
description: A dedicated and well-rounded student pursuing a future in a position in business and marketing/media. Currently working and interning in multiple business environments to get hands on experiences to allow myself to gain the knowledge to become a professional in sports marketing and the internal digital content creating side
I am seeking a career opportunity to enable me to grow and gain high level of professionalism and efficiency to create and achieve short term + long term company goal satisfaction
show_downloads: true
theme: jekyll-theme-minimal
